# Generated by Django 5.1.1 on 2024-09-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cow_id', models.CharField(max_length=8, unique=True)),
                ('color', models.CharField(choices=[('white', 'White'), ('brown', 'Brown')], max_length=5)),
                ('age_years', models.IntegerField()),
                ('age_months', models.IntegerField()),
                ('milk_bottles_produced', models.IntegerField(default=0)),
                ('is_bsod', models.BooleanField(default=False)),
            ],
        ),
    ]
