# Generated by Django 5.1.1 on 2024-09-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='almond_milk_bottles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cow',
            name='chocolate_milk_bottles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cow',
            name='plain_milk_bottles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cow',
            name='sour_milk_bottles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cow',
            name='soy_milk_bottles',
            field=models.IntegerField(default=0),
        ),
    ]
